version: "3.3"

networks:
  mcn_security:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.58.0/24

services:
  mysql:
    image: mysql:latest
    container_name: mcn_database_security
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --general-log=1 --innodb_autoinc_lock_mode=0
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data_security:/var/lib/mysql
    environment:
      MYSQL_DATABASE: MCN_TESTE_SEGURANCA
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_USER: mcn
      MYSQL_PASSWORD: qwe123
      MYSQL_HOST: mysql
      LANG: C.UTF-8
    networks:
      - mcn_security
    ports:
      - 3306:3306

  api_teste:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    image: mcn_web/app
    container_name: mcn_web_app
    env_file:
      - ./app/.env
    networks:
      - mcn_security
    ports:
      - 81:8080
    volumes:
      - ./app:/mcn_security
    stdin_open: true
    tty: true
    links:
      - mysql
    depends_on:
      - mysql

  nginx:
    image: nginx:1.18.0
    container_name: nginx_security
    networks:
      - mcn_security
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
    environment:
      - NGINX_HOST=local.local
      - NGINX_PORT=80
    depends_on:
      - api_teste

volumes:
  mcn_security:
  db_data_security:
